---
abstract: 'Get a locale specific string describing the span of a given duration'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  File::Spec: 0
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-Human-Duration
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: https://github.com/mstratman/DateTime-Format-Human-Duration
version: 0.51
